# Generated by Django 3.2.13 on 2023-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
