# Generated by Django 3.2.13 on 2023-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
